export const copy = {
  title: 'fnord-dedup2',
  subtitle: 'File inventory and dedup planning',
  database: 'Database',
  noDatabase: 'No database configured',
  navigation: 'Navigation',
  dashboard: 'Dashboard',
  upcoming: 'Future sections',
  sections: ['Scans', 'File Explorer', 'Search', 'Duplicates', 'Dedup Scenarios', 'Archives', 'Disk Images', 'Errors', 'Settings'],
  overview: 'Scanner database',
  description: 'The scanner inventory is opened read-only for each request. No source files are opened by this screen.',
  status: 'Connection status',
  loading: 'Checking database status…',
  connected: 'Ready',
  retry: 'Retry',
  locked: 'The database is currently in use by fnord-dedup2. Try again when the CLI command finishes.',
  failed: 'Database status could not be loaded.',
  schema: 'Schema versions',
  base: 'Filesystem',
  archive: 'Archives',
  image: 'Disk images',
  absent: 'Not installed',
  scanCount: 'Recorded scans',
  updated: 'Database last modified',
  readOnly: 'Read-only access',
  next: 'The scan list and directory explorer are the next implementation milestone.'
} as const;
