/** English copy is centralized so another locale can be added later. */
export const copy = {
  title: 'fnord-dedup2',
  subtitle: 'File inventory and dedup planning',
  database: 'Database',
  noDatabase: 'No database configured',
  navigation: 'Navigation',
  dashboard: 'Dashboard',
  scans: 'Scans',
  explorer: 'File Explorer',
  search: 'File Search',
  errors: 'Errors',
  upcoming: 'Future sections',
  futureSections: ['Duplicates', 'Dedup Scenarios', 'Archives', 'Disk Images', 'Settings'],
  overview: 'Database overview',
  description: 'Historical scanner observations. Source files are never opened from this interface.',
  scansDescription: 'Choose a scan to inspect its inventory, files, and recorded errors.',
  explorerDescription: 'Browse recorded directories and files.',
  errorsDescription: 'Recorded filesystem errors for this scan.',
  searchDescription: 'Filter recorded entries across scans without touching source files.',
  scanDetail: 'Scan overview',
  loading: 'Loading recorded data…',
  retry: 'Refresh',
  locked: 'The database is currently in use by fnord-dedup2. Retry when the CLI command finishes.',
  failed: 'The requested data could not be loaded.',
  readOnly: 'Read-only database',
  entries: 'Inventory entries',
  files: 'Files',
  directories: 'Directories',
  otherEntries: 'Symlinks and other entries',
  totalFileBytes: 'Total file bytes',
  hashes: 'Completed hashes',
  duplicateGroups: 'Confirmed duplicate groups',
  archiveRuns: 'Archive runs',
  imageRuns: 'Image runs',
  recentScans: 'Recorded scans',
  viewAllScans: 'View all scans',
  hashWarning: 'Only persisted size and SHA-256 hashes confirm duplicate content. Missing hashes mean unresolved, not unique.',
  noScans: 'No scans match this view.',
  noErrors: 'No recorded filesystem errors.',
  name: 'Name',
  root: 'Root',
  phase: 'Phase',
  updated: 'Updated',
  created: 'Created',
  algorithm: 'Hash algorithm',
  actions: 'Actions',
  explore: 'Explore',
  exploreFiles: 'Explore files',
  viewErrors: 'View errors',
  pendingDirectories: 'Unfinished directories',
  filterName: 'Filter scan names',
  errorFilter: 'Errors',
  allPhases: 'All phases',
  allScans: 'All scans',
  withErrors: 'With errors',
  withoutErrors: 'Without errors',
  phases: ['DISCOVERING', 'READY', 'HASHING', 'COMPLETE', 'COMPLETE_WITH_ERRORS'],
  apply: 'Apply filters',
  previous: 'Previous',
  next: 'Next',
  onPage: 'on this page',
  breadcrumbs: 'Directory breadcrumbs',
  directoryHint: 'Directories first, then files by name. Open a file for its hash and duplicate count.',
  directoryTree: 'Directory tree',
  collapse: 'Collapse ',
  expand: 'Expand ',
  more: 'More',
  folderLoadFailed: 'Folders could not be loaded. Expand to retry.',
  type: 'Type',
  size: 'Size',
  modified: 'Modified',
  hashState: 'Hash state',
  hashed: 'Hashed',
  unknownHash: 'Not hashed — unresolved',
  emptyDirectory: 'No entries in this directory.',
  fileDetails: 'File details',
  close: 'Close',
  path: 'Recorded path',
  relativePath: 'Relative path',
  sha256: 'SHA-256',
  bytes: 'bytes',
  confirmedOccurrences: 'Confirmed occurrences',
  relatedErrors: 'Related scan errors',
  historicalObservation: 'This is a historical observation; the live file is not inspected.',
  message: 'Message',
  recorded: 'Recorded',
  savedSearches: 'Saved searches',
  unsavedSearch: 'Unsaved search',
  savedName: 'Saved-search name',
  savedNamePlaceholder: 'Large videos',
  descriptionLabel: 'Description',
  savedDescriptionPlaceholder: 'Why this search matters',
  saveNew: 'Save new',
  updateSaved: 'Update',
  deleteSaved: 'Delete',
  deleteSavedConfirm: 'Delete this saved search?',
  savedNameRequired: 'Enter a saved-search name.',
  searchScope: 'Search scope',
  scanSelection: 'Selected scans',
  noScanSelection: 'No selection searches all scans. The picker shows up to 500 scans.',
  directoryScope: 'Limit to a recorded directory',
  directoryScanId: 'Directory scan ID',
  directoryEntryId: 'Directory entry ID',
  recursive: 'Include descendants',
  namesAndPaths: 'Names and paths',
  nameMatch: 'Name match',
  nameValue: 'Filename value',
  contains: 'Contains',
  startsWith: 'Starts with',
  endsWith: 'Ends with',
  exact: 'Exact',
  glob: 'Glob',
  regex: 'Regular expression',
  caseSensitive: 'Case-sensitive',
  pathContains: 'Path contains',
  pathStarts: 'Path starts with',
  pathUnder: 'Under path',
  extensions: 'Extensions',
  excludeDirectories: 'Exclude directories',
  onePathPerLine: 'One recorded relative path per line',
  attributes: 'Size, time, type, and status',
  exactSize: 'Exact size',
  minimumSize: 'Minimum size',
  maximumSize: 'Maximum size',
  modifiedAfter: 'Modified at or after',
  modifiedBefore: 'Modified at or before',
  entryTypes: 'Entry types',
  duplicateStatus: 'Duplicate status',
  any: 'Any',
  unhashed: 'Unhashed — unresolved',
  confirmedDuplicate: 'Confirmed duplicate',
  confirmed: 'confirmed occurrences',
  noConfirmedDuplicate: 'No confirmed duplicate (may be unresolved)',
  twoPlusCopies: '2+ confirmed copies',
  threePlusCopies: '3+ confirmed copies',
  acrossScans: 'Confirmed across scans',
  sortBy: 'Sort by',
  direction: 'Direction',
  ascending: 'Ascending',
  descending: 'Descending',
  pageSize: 'Page size',
  searchFiles: 'Search files',
  searchThisScan: 'Search this scan',
  searchThisDirectory: 'Search this directory',
  searching: 'Searching recorded entries…',
  scanLabel: 'Scan',
  details: 'Details',
  containingDirectory: 'Containing directory',
  hasError: 'Recorded error',
  noSearchResults: 'No recorded entries match these filters.',
  kindRequired: 'Select at least one entry type.',
  exactSizeConflict: 'Exact size cannot be combined with minimum or maximum size.',
  sizeRangeInvalid: 'Minimum size cannot exceed maximum size.',
  modifiedRangeInvalid: 'The modified start cannot be later than the end.',
  sizeFormat: 'use a number with an optional unit such as 10 MB or 2 GiB.',
  sizeTooLarge: 'value exceeds the supported byte range.',
  positiveInteger: 'enter a positive whole number.',
  invalidDate: 'enter a valid date and time.'
} as const;
