/** English copy is centralized so another locale can be added later. */
export const copy = {
  title: 'fnord-dedup2',
  subtitle: 'File inventory and dedup planning',
  database: 'Database',
  noDatabase: 'No database configured',
  navigation: 'Navigation',
  dashboard: 'Dashboard',
  scans: 'Scans',
  explorer: 'File Explorer',
  errors: 'Errors',
  upcoming: 'Future sections',
  futureSections: ['Search', 'Duplicates', 'Dedup Scenarios', 'Archives', 'Disk Images', 'Settings'],
  overview: 'Database overview',
  description: 'Historical scanner observations. Source files are never opened from this interface.',
  scansDescription: 'Choose a scan to inspect its inventory, files, and recorded errors.',
  explorerDescription: 'Browse recorded directories and files.',
  errorsDescription: 'Recorded filesystem errors for this scan.',
  scanDetail: 'Scan overview',
  loading: 'Loading recorded data…',
  retry: 'Refresh',
  locked: 'The database is currently in use by fnord-dedup2. Retry when the CLI command finishes.',
  failed: 'The requested data could not be loaded.',
  readOnly: 'Read-only database',
  entries: 'Inventory entries',
  files: 'Files',
  directories: 'Directories',
  otherEntries: 'Symlinks and other entries',
  totalFileBytes: 'Total file bytes',
  hashes: 'Completed hashes',
  duplicateGroups: 'Confirmed duplicate groups',
  archiveRuns: 'Archive runs',
  imageRuns: 'Image runs',
  recentScans: 'Recorded scans',
  viewAllScans: 'View all scans',
  hashWarning: 'Only persisted size and SHA-256 hashes confirm duplicate content. Missing hashes mean unresolved, not unique.',
  noScans: 'No scans match this view.',
  noErrors: 'No recorded filesystem errors.',
  name: 'Name',
  root: 'Root',
  phase: 'Phase',
  updated: 'Updated',
  created: 'Created',
  algorithm: 'Hash algorithm',
  actions: 'Actions',
  explore: 'Explore',
  exploreFiles: 'Explore files',
  viewErrors: 'View errors',
  pendingDirectories: 'Unfinished directories',
  filterName: 'Filter scan names',
  errorFilter: 'Errors',
  allPhases: 'All phases',
  allScans: 'All scans',
  withErrors: 'With errors',
  withoutErrors: 'Without errors',
  phases: ['DISCOVERING', 'READY', 'HASHING', 'COMPLETE', 'COMPLETE_WITH_ERRORS'],
  apply: 'Apply filters',
  previous: 'Previous',
  next: 'Next',
  onPage: 'on this page',
  breadcrumbs: 'Directory breadcrumbs',
  directoryHint: 'Directories first, then files by name. Open a file for its hash and duplicate count.',
  directoryTree: 'Directory tree',
  collapse: 'Collapse ',
  expand: 'Expand ',
  more: 'More',
  folderLoadFailed: 'Folders could not be loaded. Expand to retry.',
  type: 'Type',
  size: 'Size',
  modified: 'Modified',
  hashState: 'Hash state',
  hashed: 'Hashed',
  unknownHash: 'Not hashed — unresolved',
  emptyDirectory: 'No entries in this directory.',
  fileDetails: 'File details',
  close: 'Close',
  path: 'Recorded path',
  relativePath: 'Relative path',
  sha256: 'SHA-256',
  bytes: 'bytes',
  confirmedOccurrences: 'Confirmed occurrences',
  relatedErrors: 'Related scan errors',
  historicalObservation: 'This is a historical observation; the live file is not inspected.',
  message: 'Message',
  recorded: 'Recorded'
} as const;
